<a href="https://colab.research.google.com/github/alexandmarkov/sberbank_reboot/blob/main/Part_1_HW_Write_our_own_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

In [ ]:
%%writefile my_math_lib.py
import math
import numpy as np
from functools import reduce


def deg_to_rad(degrees):
    """Преобразование градусов в радианы"""
    return degrees * math.pi / 180


def rad_to_def(radians):
    """Преобразование радиан в градусы"""
    return radians * 180 / math.pi


def discriminant(a, b, c):
    """Вычисление дискриминанта"""
    return b**2 - 4*a*c


def power_base_sum(a, b):
    """Сумма всех цифр основания в указанной степени"""
    return sum([int(num) for num in str(a**b) if num.isdigit()])


def magic_square(n):
    """Вычисление магического квадрата"""
    arr = np.zeros(shape=(n, n), dtype=np.int16)
    i = n / 2
    j = n - 1
    num = 1
    while num <= (n**2):
        if i == -1 and j == n:
            j = n - 2
            i = 0
        else:
            if j == n:
                j = 0
            if i < 0:
                i = n - 1
        
        if arr[int(i)][int(j)]:
            j = j - 2
            i = i + 1
            continue
        else:
            arr[int(i)][int(j)] = num
            num += 1
        j += 1
        i -= 1
    return arr


def mult_list(lst: list):
    """Умножение всех чисел в массиве"""
    filter_list = list(filter(lambda x: str(x).isdigit(), lst))
    return reduce(lambda x, y: x*y, filter_list)


def create_list():
    """Печатает и возвращает массив квадратов чисел от 1 до 30"""
    lst = [i**2 for i in range(1, 31)]
    print(lst)
    return lst

Overwriting my_math_lib.py


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [ ]:
from my_math_lib import *

In [ ]:
print(discriminant(1, 3, 4))

-7


In [ ]:
print(magic_square(5))

[[ 9  3 22 16 15]
 [ 2 21 20 14  8]
 [25 19 13  7  1]
 [18 12  6  5 24]
 [11 10  4 23 17]]


# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [ ]:
%%writefile my_math_lib.py
import sys
import math
import numpy as np
from functools import reduce


n = int(sys.argv[1])


def deg_to_rad(degrees):
    """Преобразование градусов в радианы"""
    return degrees * math.pi / 180


def rad_to_def(radians):
    """Преобразование радиан в градусы"""
    return radians * 180 / math.pi


def discriminant(a, b, c):
    """Вычисление дискриминанта"""
    return b**2 - 4*a*c


def power_base_sum(a, b):
    """Сумма всех цифр основания в указанной степени"""
    return sum([int(num) for num in str(a**b) if num.isdigit()])


def magic_square(n):
    """Вычисление магического квадрата"""
    arr = np.zeros(shape=(n, n), dtype=np.int16)
    i = n / 2
    j = n - 1
    num = 1
    while num <= (n**2):
        if i == -1 and j == n:
            j = n - 2
            i = 0
        else:
            if j == n:
                j = 0
            if i < 0:
                i = n - 1
        
        if arr[int(i)][int(j)]:
            j = j - 2
            i = i + 1
            continue
        else:
            arr[int(i)][int(j)] = num
            num += 1
        j += 1
        i -= 1
    return arr


def mult_list(lst: list):
    """Умножение всех чисел в массиве"""
    filter_list = list(filter(lambda x: str(x).isdigit(), lst))
    return reduce(lambda x, y: x*y, filter_list)


def create_list():
    """Печатает и возвращает массив квадратов чисел от 1 до 30"""
    lst = [i**2 for i in range(1, 31)]
    print(lst)
    return lst


if __name__ == "__main__":
    print(magic_square(n))

Overwriting my_math_lib.py


In [ ]:
!python3 my_math_lib.py 5

[[ 9  3 22 16 15]
 [ 2 21 20 14  8]
 [25 19 13  7  1]
 [18 12  6  5 24]
 [11 10  4 23 17]]
